services:
  - name: uuidService
    type: grpc
    target: '127.0.0.1:9001'
    protoPath: '../proto/uuid.proto'
    authRequired: false
    methods:
      - name: GenerateUUID
        request:
          prefix: string
        validation:
          prefix: 
            type: string
            required: true
      - name: Watch
        request:
          prefix: string
  - name: workoutService
    type: rest
    target: '127.0.0.1:3008'
    authRequired: false
    methods:
      - name: POST
        path: /workout
        request:
          userId: string
        validation:
          userId: 
            type: string
            required: true
      - name: GET
        path: /workouts/{userId}