services:
  - name: workoutService
    type: rest
    target: '127.0.0.1:3008'
    authRequired: false
    routes:
      - path: /workouts
        methods:
          - name: POST
            request:
              userId: string
            validation:
              userId: 
                type: string
                required: true
      - path: /workouts/:userId/workout/:workoutId
        description: Get a user workout by id
        methods:
          - name: GET
      - path: /workouts/:userId
        methods:
          - name: GET
      - path: /exercise/:exerciseId/history
        methods:
          - name: GET
            request:
              userId: string
              workoutId: string
            validation:
              userId: 
                type: string
                required: true
              workoutId:
                type: string
                required: true